Style/refactoring auth
swm-null/null_front pull request #32
Opened 2024-07-25 06:06 UTC by gee2450

# 🔥 연관 이슈
- close #30 

# 🚀 작업 내용
1. style: auth를 기능(dashboard, default, memo)로 분리하여 코드 저장

# 💬 리뷰 중점사항
1. 

# 🖼 스크린샷 (선택)

2024-07-25 18:14 UTC, BaeJinho4028 approved these changes
좋습니다. 
근데 default는 어떤 경우일까요? dash보드와 memo외에 다른 경우가 무엇이죠??

2024-07-25 18:14 UTC, BaeJinho4028 commented on src/utils/auth/default/checkValid.ts
> +  const validStatus = [200, 201, 202, 203, 204, 205, 206];
이거 상태코드인가요? 저희가 이렇게 많이쓰던가요?

2024-07-25 18:14 UTC, BaeJinho4028 commented on src/utils/auth/default/handleError.ts
> +    // 요청을 설정하는 동안 문제가 발생했습니다.
if-else 줄넘김이 뭔가 불규칙적인것같습니다.

2024-07-27 08:31 UTC, gee2450 commented on src/utils/auth/default/checkValid.ts
> +  const validStatus = [200, 201, 202, 203, 204, 205, 206];
아뇨...그냥 나중에 쓸 가능성 있을까봐 다 넣었었는데 생각해보니 헷갈리겠네요. 줄일께요

2024-07-27 08:32 UTC, gee2450 commented on src/utils/auth/default/handleError.ts
> +    // 요청을 설정하는 동안 문제가 발생했습니다.
음...주석 때문에 잘 보라고 일부러 넣었는데 오히려 if else 라는게 잘 안 보이긴 하네요. 이거 수정할께요

2024-07-27 11:17 UTC, gee2450 commented
> 좋습니다. 근데 default는 어떤 경우일까요? dash보드와 memo외에 다른 경우가 무엇이죠??

default(현재 이름 global로 수정)는 전체 프로젝트에서 쓰는 에러 핸들링과 validResponse, errorResponse 형식 파일을 저장한 폴더 입니다. 
dashboard 폴더는 말 그대로 대시보드에서 쓰는 메소드 파일을 저장한 폴더이고,
memo 폴더는 memo 그 자체의 crud 메소드 파일을 저장한 폴더입니다.

2024-07-27 11:19 UTC, r4pidstart commented on src/utils/auth/global/checkValid.ts
> +  const validStatus = [200, 201, 204];
뭔가 enum같은 상수가 어딘가에 정의되어 있을 것 같긴 한데

2024-07-27 11:20 UTC, r4pidstart commented on src/utils/auth/global/interface.ts
> +export interface validResponse extends response {}
```suggestion
}

export interface validResponse extends response {}
```

2024-07-27 11:23 UTC, r4pidstart commented on src/utils/auth/memo/memoApi.ts
> +};
헤더 넣어주는 것도 그렇고 중복된 부분이 너무 많이 보여요.

2024-07-27 11:24 UTC, r4pidstart commented on src/utils/auth/memo/interface.ts
> +export interface cuMemoResponse extends Memo, validResponse {}
이 친구는 이름 바꿔주는게 좋아보여요

2024-07-27 11:26 UTC, r4pidstart commented on src/utils/auth/memo/checkValid.ts
> +  return (response as cuMemoResponse).content !== null;
이거 불필요할텐데

2024-07-27 11:30 UTC, r4pidstart commented on src/utils/auth/dashboard/dashboardApi.ts
> +  const method = 'getChildTags';
직접 쓰지 말고 function.name 쓰세요

2024-07-27 11:33 UTC, r4pidstart requested changes
> > 좋습니다. 근데 default는 어떤 경우일까요? dash보드와 memo외에 다른 경우가 무엇이죠??

default(현재 이름 global로 수정)는 전체 프로젝트에서 쓰는 에러 핸들링과 validResponse, errorResponse 형식 파일을 저장한 폴더 입니다. 
dashboard 폴더는 말 그대로 대시보드에서 쓰는 메소드 파일을 저장한 폴더이고,
memo 폴더는 memo 그 자체의 crud 메소드 파일을 저장한 폴더입니다.  

global보다는 뭐 하는 파일들이 있는 폴더인지 알 수 있는 편이 좋을 것 같은데. 지금 파일들 보면 다 리스폰스 핸들링 관련된 무언가네요

2024-07-27 12:45 UTC, gee2450 commented on src/utils/auth/memo/interface.ts
> +export interface cuMemoResponse extends Memo, validResponse {}
흠...memo create, update 때 둘다 써서 이렇게 했는데 좀 너무 축약했나..흠...

2024-07-27 12:48 UTC, gee2450 commented on src/utils/auth/memo/checkValid.ts
> +  return (response as cuMemoResponse).content !== null;
as 이거요?

2024-07-27 12:55 UTC, r4pidstart commented on src/utils/auth/memo/checkValid.ts
> +  return (response as cuMemoResponse).content !== null;
yes

2024-07-29 08:55 UTC, gee2450 commented on src/utils/auth/memo/interface.ts
> +export interface cuMemoResponse extends Memo, validResponse {}
cuMemoResponse 별론가..? 
create, update response라 했는데 그냥 직관적이게 createUpdateMemoResponse가 더 괜찮은가요?

2024-07-29 08:57 UTC, gee2450 commented on src/utils/auth/memo/checkValid.ts
> +  return (response as cuMemoResponse).content !== null;
as 없애보려고 계속 노력했지만, 어디선가 빨간 줄이 뜹니다. 안돼 돌아가

2024-07-29 09:01 UTC, gee2450 commented on src/utils/auth/dashboard/dashboardApi.ts
> +  const method = 'getChildTags';
넵~

2024-07-31 15:16 UTC, r4pidstart commented on src/utils/auth/memo/memoApi.ts
> +
급한거 아니니까 나중에 생각을 좀 해봅시다

2024-08-20 06:40 UTC, gee2450 commented
나중에 다시 하겠습니다. 현재 auth 파일을 다른 branch에서 더 좋은 방식으로 수정해서 이번 PR 닫겠습니다.

2024-08-20 06:40 UTC, closed without merging