[NULL-211] Feature/dropzone 화면 퍼블리싱
swm-null/null_front pull request #33
Opened 2024-07-30 09:51 UTC by gee2450

# 🔥 연관 이슈
- close #31 

# 🚀 작업 내용
1. 카카오톡 csv 파일 업로드 하는 화면 퍼블리싱

# 💬 리뷰 중점사항
저번 스크럼 때 모바일은 csv 파일을 메일로 보내 자동으로 확인하고 메모를 추가해 주는 로직을 쓰기로 결정했지만, 
해당 내용을 구현하기까지 오래 걸릴 것 같기 때문에, 직접 csv를 올리는 임시 화면 퍼블리싱

# 🖼 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/1f0a7075-89d7-4932-ab5b-77d33c88e393)

2024-07-31 15:20 UTC, r4pidstart requested changes
@components 폴더 이름 바꿉시다

2024-07-31 23:30 UTC, gee2450 commented on src/pages/home/sidebar/SideBar.tsx
> +          </button>
아 사이드바 내부 컴퍼넌트 그러게요 왜 이 생각 안했지..?

2024-07-31 23:41 UTC, gee2450 commented
> @components 폴더 이름 바꿉시다

그거....파일 31개 바뀌어..

2024-08-01 09:05 UTC, BaeJinho4028 approved these changes

2024-08-01 09:05 UTC, BaeJinho4028 commented on src/pages/home/contents/UploadDataPage/KakaoDropzone/KakaoDropzone.tsx
> +        <></>
이건 뭔가요?? 원래 필요한것인가요?

2024-08-01 09:05 UTC, BaeJinho4028 commented on src/pages/home/contents/UploadDataPage/KakaoDropzone/KakaoDropzone.tsx
> +        <p className="text-center">Only *.csv files will be accepted</p>
이것도 나중에는 언어 바꿔주시면 좋을 것 같습니다

2024-08-02 01:59 UTC, gee2450 commented on src/pages/home/contents/UploadDataPage/KakaoDropzone/KakaoDropzone.tsx
> +        <p className="text-center">Only *.csv files will be accepted</p>
좋아영 어차피 8월 1일 스크럼 때, 어떻게 텍스트 써야 하는지 감이 잡혀서 화면 리퍼블리싱 할때 i18n으로 관리하겠습니다~

2024-08-02 01:59 UTC, gee2450 commented on src/pages/home/contents/UploadDataPage/KakaoDropzone/KakaoDropzone.tsx
> +        <></>
<></>이거요?

2024-08-02 02:16 UTC, merged