[NULL-351] Feature/ create rebuild
swm-null/null_front pull request #49
Opened 2024-09-25 08:46 UTC by gee2450

# 🔥 연관 이슈
- close #NULL-351

# 🚀 작업 내용
1. 메모 추가 화면의 font style 변경
2. margin 대신 gap과 padding을 사용하며 메모 추가 화면 style 변경

# 💬 리뷰 중점사항
1. 

# 🖼 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/a2b17d45-db1f-41ef-b30c-c534be316916)

2024-09-25 10:09 UTC, BaeJinho4028 approved these changes
좋습니다.

2024-09-25 10:09 UTC, BaeJinho4028 commented on src/i18n/locales/ko.json
> +      "inputPlaceholder": "입력 프롬프트",
여기는 왜 메모 검색... 이 아닌가요?

2024-09-25 10:09 UTC, BaeJinho4028 commented on src/i18n/locales/ko.json
> +      "inputPlaceholder": "메모 작성...",
... 은 넣는것이 좋을지. 차라리 텍스트를 안넣는게 나을지 잘 모르겠네요. 일단 써보며 맞춰보죠

2024-09-25 12:28 UTC, r4pidstart requested changes
> 일단. 스샷 메모색이랑 검색창 색이 안맞습니다. 

rgb 코드 그대로 박혀있던데 이런거 쓰는것도 추천은 드리구요. 시간많으면 하셈
https://velog.io/@boorook/Tailwind-CSS%EC%97%90%EC%84%9C-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%BB%AC%EB%9F%AC-%EC%84%A4%EC%A0%95
https://tailwindcss.com/docs/customizing-colors

2024-09-26 06:43 UTC, gee2450 commented on src/i18n/locales/ko.json
> +      "inputPlaceholder": "입력 프롬프트",
사실 디자인에 없길래 걍..핳 메모 검색...이 더 좋은것 같나요?

2024-09-26 06:44 UTC, gee2450 commented on src/i18n/locales/ko.json
> +      "inputPlaceholder": "메모 작성...",
이건 디자인이 저러길래 그냥 했습니다.

2024-09-26 06:45 UTC, gee2450 commented
> 메모색이랑 검색창 색이 안

아 메모 색 안 바꿨다. 감사합니다. 눈이 침침한가 둘이 다른 줄 몰랐어요..어우..

2024-09-26 06:45 UTC, BaeJinho4028 commented on src/i18n/locales/ko.json
> +      "inputPlaceholder": "입력 프롬프트",
메모 추가와 검색의 형식을 통일 하는것이 좋다고 생각했습니다. 일단은 메모 추가, 메모 검색으로 통일해주시죠

2024-09-26 07:10 UTC, gee2450 commented
> > 일단. 스샷 메모색이랑 검색창 색이 안맞습니다.
> 
> rgb 코드 그대로 박혀있던데 이런거 쓰는것도 추천은 드리구요. 시간많으면 하셈 https://velog.io/@boorook/Tailwind-CSS%EC%97%90%EC%84%9C-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%BB%AC%EB%9F%AC-%EC%84%A4%EC%A0%95 https://tailwindcss.com/docs/customizing-colors

이거 하려 했는데, 디자이너님이 색 이름을 따로 정해서 디자인 해주신게 아니라, 제가 직접 색 확인하고 정리해야하더라고요.
그래서 색 이름 어캐 지어야할지 모르겠어서, 나중에 한번 싹 모아서 할께요.

2024-09-27 04:17 UTC, r4pidstart approved these changes

2024-09-27 08:47 UTC, merged