[NULL-323] Feature/dashboard design
swm-null/null_front pull request #54
Opened 2024-10-04 02:28 UTC by gee2450

# 🔥 연관 이슈
- close #NULL-323

# 🚀 작업 내용
1. Tag 컴포넌트 tailwind-variants 사용하게 수정
2. Memo 컴포넌트 파라미터 수정
3. 사이드바 뒤의 내용이 클릭 안 되는 오류 수정
4. 대시보드 핀 내용 미리 구현
5. 메모 수정 모달 디자인 반영
6. 메모 수정 모달 안 닫히는 버그 수정

# 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/6a3bb94d-81c0-460f-a0f0-8b5d9c3d4736)
![image](https://github.com/user-attachments/assets/413095c1-9f5e-4782-949e-c2cdd6c0fb82)
![image](https://github.com/user-attachments/assets/33c55395-6943-451e-b3ae-1cfcb9f83cf5)

# 💬 리뷰 중점사항

2024-10-05 04:14 UTC, r4pidstart requested changes

2024-10-05 04:14 UTC, r4pidstart commented on src/api/refreshableApi/memoApi.ts
> +  const endpoint = `/tag/memos?tagId=${tagId}&sortOrder=LATEST`;
야는 다른 정렬이 들어갈 여지가 없어요?

2024-10-05 04:14 UTC, r4pidstart commented on src/pages/home/subPages/components/memo/EditableMemo/EditableMemo.tsx
>      <div
요부분도 좀 쪼개서 정리해주믄 좋겠다.

2024-10-06 10:40 UTC, BaeJinho4028 reviewed
메모 이름순 정렬만 제거 부탁드릴게요

2024-10-06 10:40 UTC, BaeJinho4028 commented on src/i18n/locales/ko.json
> +        "name": "이름순"
메모는 이름순이 없으니 제거 부탁드립니다.

2024-10-06 10:40 UTC, BaeJinho4028 commented on src/pages/home/subPages/components/ui/EditableTag/EditableTag.tsx
> +  className, // 추가된 부분
주석이 필요한가요?

2024-10-06 10:40 UTC, BaeJinho4028 commented on src/pages/home/subPages/main/Main.tsx
>      // 50vh - (토글+여백+TextArea 기본 높이) - 사이드바 절반 높이
이건 아직 해결방법은 못찾은 것일까요?

2024-10-06 14:17 UTC, gee2450 commented on src/api/refreshableApi/memoApi.ts
> +  const endpoint = `/tag/memos?tagId=${tagId}&sortOrder=LATEST`;
아직 api 연동 제대로 안해서 그냥 디자인 보이겠끔만 넣었습니다. api연동은 페이지네이션 하면서 같이 할 예정입니다.

2024-10-07 01:42 UTC, gee2450 commented on src/i18n/locales/ko.json
> +        "name": "이름순"
걔 아예 api에는 있던데, 그거 삭제 예정인가요? 아니면 서버가 옛날버전인가요?

2024-10-07 01:44 UTC, gee2450 commented on src/pages/home/subPages/components/ui/EditableTag/EditableTag.tsx
> +  className, // 추가된 부분
앗 실수

2024-10-07 02:10 UTC, gee2450 commented on src/pages/home/subPages/components/memo/EditableMemo/EditableMemo.tsx
>      <div
EditableMemo, UneditableMemo 둘다 컴포넌트 따로 만들어서 정리했습니다.

2024-10-07 02:13 UTC, gee2450 commented on src/i18n/locales/ko.json
> +        "name": "이름순"
태그이름순 확인

2024-10-07 02:19 UTC, merged