feat: home에 있던 token이 유효한지 확인하는 코드를, ApiProvider로 이동
swm-null/null_front pull request #55
Opened 2024-10-04 12:44 UTC by gee2450

# 🔥 연관 이슈
- close #NULL-381

# 🚀 작업 내용
1. refresh 오류 수정
2. redirect 오류 수정

# 스크린샷 (선택)

# 💬 리뷰 중점사항

2024-10-04 13:08 UTC, BaeJinho4028 requested changes
좋습니다. 한가지만 체크 부탁드려요!

2024-10-04 13:08 UTC, BaeJinho4028 commented on src/utils/provider/ApiProvider.tsx
> +      const isRefreshTokenExpired = (status: number) => status === 403;
401이어야하지 않나요?

2024-10-05 03:16 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +      const isRefreshTokenExpired = (status: number) => status === 403;
그거 여기서 안하게요, 악 이거 전에 머지 기다렸다가, 오래걸릴 것 같아서, 유기하고 PR 올린거라 머지 된걸 까먹고 있었네요. ㅇㄴ

2024-10-05 04:52 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +      const isRefreshTokenExpired = (status: number) => status === 403;
바꿈! 아싸

2024-10-05 09:13 UTC, BaeJinho4028 approved these changes

2024-10-05 09:13 UTC, BaeJinho4028 commented on src/utils/provider/ApiProvider.tsx
> +    isTokenExpired(status) && code === '0004';
`0003`, `0004` 부분을 상수화하는 것도 좋을것 같아요

2024-10-05 10:58 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +    isTokenExpired(status) && code === '0004';
여기서밖에 안써서 그냥 여기서 함수로만 사용했는데 상수화를 해야할까요? 흠..

2024-10-06 08:42 UTC, r4pidstart approved these changes
로직이 중복된 부분이 좀 있는 것 같긴 한데 뭐 돌아가면 됐죠

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +      setRedirectLogin(true);
이거 이렇게 할거면 그냥 redirectLogin함수를 만들어서 부르는게 낫지 않나요

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +  const alertLoginRequired = () => {
글고 이건 alert만 띄우는게 아니잔슴

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +      setRedirectLogin(true);
함수 부르면 alert accept 안 해도 넘어감?

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +  }, [redirectLogin]);
navigate 이후에 redirectLogin을 false로 안 바꾸는 이유 있어요?

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +      setRedirectLogin(false);
그러면 이런 부자연스러운 로직 안 넣어도 될 것 같은데

2024-10-06 08:42 UTC, r4pidstart commented on src/utils/provider/ApiProvider.tsx
> +    }
그리고 이미 getAccessToken이랑 interceptor error handler에서 익셉션은 다 잡아주잖아요 그럼 그냥 config.headers['Authorization'] = `Bearer ${accessToken}`; 만 써도 될 것 같은데

2024-10-06 09:13 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +      setRedirectLogin(true);
알림 확인 버튼 하나 있고, 그거 클릭하면 redirect 합니다

2024-10-06 09:15 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +    }
맞네요. 수정후 머지할께요

2024-10-06 09:16 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +      setRedirectLogin(false);
이거 없애고 useEffect에서 할께요

2024-10-06 09:24 UTC, gee2450 commented on src/utils/provider/ApiProvider.tsx
> +  }, [redirectLogin]);
navigate 전에 false로 바꾸게 수정했습니다.

2024-10-06 09:25 UTC, merged

2024-10-06 09:26 UTC, BaeJinho4028 commented on src/utils/provider/ApiProvider.tsx
> +    isTokenExpired(status) && code === '0004';
뭐 전체적으로 상수 정리하는거 있으면 좋긴할거같은데 일단 이대로 가보죠. 크리티컬하진 않으니