Feature/connect search with be
swm-null/null_front pull request #6
Opened 2024-06-23 09:30 UTC by gee2450

# 🔥 연관 이슈
NULL-54 ← jira 이슈 번호

# 🚀 작업 내용
1. 글씨체 Pretendard로 설정
2. css 작업(color, font size)
3. backend에 request를 보내로, response 받은 것을 화면에 표시
   - 관련 메모 리스트를 반환 하는 경우 표시
   - 관련 메모가 없을 경우 "관련된 메시지가 없습니다" 표시
4. localStorage 파일 분리와 이름 수정
   - localStorage 저장 이름 수정
   - SearchPage.tsx에 있던 코드 useCachedSearchQueries.tsx로 분리

# 스크린샷 (선택)
수정 전 → 수정 후
<p align:'center'>
   <img width="41%" alt="image" src="https://github.com/swm-null/null_front/assets/65989738/ff343862-970f-4376-897a-7279a5618ed0">
   <img width="58%" alt="image" src="https://github.com/swm-null/null_front/assets/65989738/37d0a7df-9c01-4ac2-a2df-97328782ad2c">
</p>

# 💬 리뷰 중점사항
자유

2024-06-23 13:27 UTC, BaeJinho4028 approved these changes
멋있어요

2024-06-23 13:27 UTC, BaeJinho4028 commented on tailwind.config.js
> +        '5/12' :  '41.666667%',
이게 머람용

2024-06-24 06:59 UTC, gee2450 commented on tailwind.config.js
> +        '5/12' :  '41.666667%',
저거...tailwind classname 기본 주어진 게 퍼센트가 없어서 하나 만들 겸 다 만들었습니다..핳

2024-06-24 12:37 UTC, r4pidstart requested changes

2024-06-24 12:38 UTC, gee2450 commented on src/search/component/SearchInput.tsx
> +    var answer;
좋아요 바꿀께요. 이거 하고 다시 올릴께여

2024-06-24 12:39 UTC, gee2450 commented on src/search/component/SearchInput.tsx
> +    return answer;
오 좋다 매우 감사감사

2024-06-25 02:36 UTC, gee2450 commented on src/search/component/SearchInput.tsx
> +    var answer;
밑에 if문을 삼항 연산자로 사용하여 answer를 const로 바로 선언하게 수정 완료

2024-06-25 02:36 UTC, gee2450 commented on src/search/component/SearchInput.tsx
> +    return answer;
수정했습니다~!

2024-06-25 02:40 UTC, gee2450 commented on src/search/hook/useCachedSearchQueries.tsx
> +  });
음.. 이거는 코드 존재 여부를 다시 생각해봐야할 것 같은데, load cache를 처음에 만들어야지 한게, 
1. cache에서 검색결과를 다 가져오는 것이 오래 걸릴 것 같아
2. 그럼 일부분(20개)만 가져와서 추가로 계속 로딩해야지~!
3. (코딩 작업)
4. 어 localStorage에는 너무 많은 정보를 저장할 수 없네..? 그럼 200개만 해야지
5. 200개면 바로 불러와지는데...?
이 흐름으로 코딩한거라 아예 코드를 없앨지 localStorage 말고 따로 디비를 사용해서 200개보다 더 많이 저장할지 고민이 됩니다.

2024-06-25 02:41 UTC, gee2450 commented on src/util/auth.tsx
> +}
악 안 지웠다 지울께요

2024-06-25 03:04 UTC, gee2450 commented on tailwind.config.js
> +        '5/12' :  '41.666667%',
50%, 25%, 10% 단위만 살려놓았습니다

2024-06-25 03:12 UTC, gee2450 commented on src/search/component/SearchInput.tsx
> +  };
주석 쓰기 싫어서 분리한건데, 그럼 합치고 따로 코드 설명 주석만 추가하겠습니다~

2024-06-26 01:11 UTC, r4pidstart commented on src/search/hook/useCachedSearchQueries.tsx
> +  });
ㅋㅋ 항상 파일에 접근하는게 오래걸리지 읽기 시작하면 읽는 양은 생각보다 속도에 영향이 없어요
디비를 쓴다는거면 백엔드쪽에 채팅 데이터를 저장한다는 뜻?
근데 이러면 반응이 좀 느려서 캐시를 쓰면 좋을 것 같긴 한데

2024-06-26 01:13 UTC, r4pidstart approved these changes
고생

2024-06-26 07:19 UTC, gee2450 commented on src/search/hook/useCachedSearchQueries.tsx
> +  });
백엔드 디비 말고 클라이언트 쪽에 db가 따로 있던데, IndexedDB 사용하게 수정할까 생각했습니다. 
그런데 검색 결과를 그렇게 열심히 볼까 싶어서 이걸 사용하는 것이 맞을지는 좀더 생각해 봐야할 것 같습니다.

2024-06-26 07:27 UTC, gee2450 commented on src/search/hook/useCachedSearchQueries.tsx
> +  });
오케이 그냥 load 해오는 기능 뺄께요. 그냥 처음부터 다 보여줘도 로딩 속도는 비슷할 것 같네요

2024-06-26 08:22 UTC, merged