[NULL-462] Feature/dashboard
swm-null/null_front pull request #67
Opened 2024-10-19 06:22 UTC by gee2450

# 🔥 연관 이슈
- close #NULL-462

# 🚀 작업 내용
1. 페이지네이션 api 수정
2. 페이지네이션 api를 memoApi에서 paginationApi로 이동
3. 기존에 fetchNextPage를 할때, 직접 하나의 InfiniteQuery로 데이터를 직접 집어넣던 것을 tag infinite query, 메모들 각자 infinite query로 관리하게 수정

# 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/e8510b56-fb89-4c63-b8bd-0fe05b5049f9)
- 빨간색, 파란색끼리 infiniteQuery 관리
- 이때 파란색은 네모마다 각각 관리
![image](https://github.com/user-attachments/assets/231ba3bf-9ad2-41bb-bfc8-f412e358a836)
![image](https://github.com/user-attachments/assets/8e86edbd-0120-44d7-9f2d-163183dabcad)

# 💬 리뷰 중점사항
const updateMemoFromMemoSectionList = (_memo: Memo) => {
   // TODO: 여기서 모든 섹션마다 해당 메모를 찾아서 업데이트 해주는 코드 들어가야함
};

const deleteMemoFromMemoSectionList = (_memoId: string) => {
   // TODO: 여기서 모든 섹션마다 해당 메모를 찾아서 업데이트 해주는 코드 들어가야함
};

const revertMemoFromMemoSectionList = (_memo: Memo) => {
   // TODO: 여기서 모든 섹션마다 해당 메모를 찾아서 업데이트 해주는 코드 들어가야함
};
이 부분 구현 안했는데, context로 대시보드 메모 내용 빼고 background에서 관리를 해야 가능할 것 같아서, 다른 이슈 하고 하겠습니다. 
이 부분은 무시해주세요.

2024-10-19 10:36 UTC, BaeJinho4028 requested changes
고생하셨습니다! 몇가지부분만 체크해주실수있을까요?

2024-10-19 10:36 UTC, BaeJinho4028 commented on src/api/refreshableApi/paginationApi.ts
> +  sortOrder: SortOption;
sortOption으로 해드릴걸 그랬나요??

2024-10-19 10:36 UTC, BaeJinho4028 commented on src/api/refreshableApi/paginationApi.ts
> +  searchHistoryLimit?: number;
이거 이제 page limit으로 바꼈어요

2024-10-19 10:36 UTC, BaeJinho4028 commented on src/api/refreshableApi/paginationApi.ts
> +    undefined
이거 굳이 줄넘김이 있어야하나요??

2024-10-19 10:36 UTC, BaeJinho4028 commented on src/api/refreshableApi/paginationApi.ts
> +    undefined
여기도

2024-10-19 10:36 UTC, BaeJinho4028 commented on src/pages/home/subPages/dashboard/Dashboard.tsx
> +  };
저희 나중에 메모 정리중일때 대시보드 들어가면 아직 생성중이다 라는거를 보여주는게 있으면 좋긴할거같은데 차차 고민해보죠
저도 최대한 시간을 줄여보겠습니다

2024-10-19 10:43 UTC, gee2450 commented on src/api/refreshableApi/paginationApi.ts
> +  searchHistoryLimit?: number;
헐 헐헐헐

2024-10-19 10:43 UTC, gee2450 commented on src/api/refreshableApi/paginationApi.ts
> +    undefined
이거 한줄 너무 길어지면 자동으로 넘어가게 vscode 설정해놓은 거에요

2024-10-19 10:45 UTC, BaeJinho4028 commented on src/api/refreshableApi/paginationApi.ts
> +    undefined
근데 저게 라인포매팅이 컨벤션에 맞는지 궁금해서 여쭤봤습니다.

```
(response as paginationDashboardTagRelationsResponse)
    .tag_relations !== undefined
```

저라면 이렇게 할것같습니다.

2024-10-19 11:00 UTC, gee2450 commented on src/api/refreshableApi/paginationApi.ts
> +    undefined
세부 조정이 안되서 그냥 response 이름 좀 간략하게 해서 한줄로 만들거나, prettier로 한줄 길이를 길게하는 수밖에 없을 것 같아요.
아니면 아예 prettier를 끄는 방법도..

2024-10-19 14:06 UTC, BaeJinho4028 approved these changes

2024-10-19 14:38 UTC, r4pidstart approved these changes

2024-10-19 14:38 UTC, r4pidstart commented on src/pages/home/subPages/dashboard/components/MemoSectionList/LeafMemoList/LeafMemoList.tsx
> +const LeafMemoList = ({
얘도 section이 돼야죠. leafTag의.

2024-10-19 14:38 UTC, r4pidstart commented on src/pages/home/subPages/dashboard/Dashboard.tsx
> +  };
이건 그냥 한번 다시 갖고오는게 편하지 않음?

2024-10-20 01:43 UTC, gee2450 commented on src/pages/home/subPages/dashboard/Dashboard.tsx
> +  };
전 또 생각중인게, 화면에 있는 태그의 메모면 캐시로 보여주고, 없는 태그면 안 보여줘도 될것 같기도 해서 흠...

2024-10-20 05:33 UTC, gee2450 commented on src/pages/home/subPages/dashboard/components/MemoSectionList/LeafMemoList/LeafMemoList.tsx
> +const LeafMemoList = ({
근데 고민중인게, 섹션으로 보이는게 아니라 3번째 이미지처럼 보여서 Section이라 해도 될까 고민..

2024-10-20 05:35 UTC, merged